name: Deploy Hugo site to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: '0.144.0'

    - name: Remove old publication
      run: rm -rf public

    - name: Checking out gh-pages branch
      run: |
        git worktree add -B gh-pages public origin/gh-pages || git worktree add -b gh-pages public

    - name: Replace secrets in hugo.toml
      run: |
        sed -i 's/\$GITALK_CLIENT_ID/${{ secrets.GITALK_CLIENT_ID }}/g' hugo.toml
        sed -i 's/\$GITALK_CLIENT_SECRET/${{ secrets.GITALK_CLIENT_SECRET }}/g' hugo.toml

    - name: Generate site
      env:
        HUGO_ENV: "production"
      run: hugo -t github-style

    - name: Configure git
      run: |
        git config --global user.email "nhandev10@gmail.com"
        git config --global user.name "Tran Huu Nhan"

    - name: Commit and push changes
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        cd public
        git add --all
        git commit -m "Publishing to gh-pages" || echo "No changes to commit."
        git push origin gh-pages
